identify_language:
  description: >
    Given the user prompt, identify its language so you are able to
    respond in the same language.

    User prompt: {prompt}.
  expected_output: >
    A phrase like "The language of the user prompt is 'language'."
    Examples:
    - The language of the user prompt is Brazilian Portuguese (pt-BR)
    - The language of the user prompt is English (en-US)
    - The language of the user prompt is Japanese (ja-JP)
  agent: linguist

research_proper_answer:
  description: >
    Given the user prompt, research for a proper answer.

    User prompt: {prompt}.

    GUIDELINES
    ===========
    - Always use the QdrantVectorSearchTool to search for anything related to CrewAI
    - This tool only accepts queries written in en-US language
    - Interact with it multiple times if necessary to get a high-quality answer. However, be mindful of the cost of the interactions. You need to respond fast, so plan ahead
    - If you find a file that is highly connected to the user prompt, get all its content through filter_by (metadata.file_path) and filter_value parameters repeating the same query parameter
  expected_output: >
    The answer in Markdown format respecting the language of the user prompt.
  context:
    - identify_language
  markdown: true
  agent: crewai_expert
